# Generated by Django 4.2.28 on 2026-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, upload_to="product_images/%y/%m/%d"),
        ),
    ]
